# Generated by Django 4.2.29 on 2026-03-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="课程代码"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4f46e5",
                        help_text="十六进制颜色代码，用于在 UI 中区分不同课程",
                        max_length=7,
                        verbose_name="标签颜色",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待完成"),
                            ("in_progress", "进行中"),
                            ("done", "已完成"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["due_date", "-priority"],
            },
        ),
    ]
